services:
  etcd0: &etcd
    image: quay.io/coreos/etcd:v3.5.16
    ports:
      - 2379
      - 2380
      - 4001
    entrypoint:
      - etcd
      - --enable-v2
      - --listen-client-urls=http://0.0.0.0:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=mys3cr3ttok3n
    command:
      - --name=etcd0
      - --advertise-client-urls=http://etcd0:2379
      - --initial-advertise-peer-urls=http://etcd0:2380
    volumes:
      - etcd0:/etcd_data
  etcd1:
    <<: *etcd
    command:
      - --name=etcd1
      - --advertise-client-urls=http://etcd1:2379
      - --initial-advertise-peer-urls=http://etcd1:2380
    volumes:
      - etcd1:/etcd_data
  etcd2:
    <<: *etcd
    command:
      - -name=etcd2
      - -advertise-client-urls=http://etcd2:2379
      - -initial-advertise-peer-urls=http://etcd2:2380
    volumes:
      - etcd2:/etcd_data

volumes:
  etcd0:
  etcd1:
  etcd2:
