services:
  etcd0: &etcd
    image: quay.io/coreos/etcd:v3.5.16
    # internal: 2379 for client communication
    # internal: 2380 for etcd nodes communication
    # localhost: 2379 for client communication
    # localhost: 2380 for etcd nodes communication
    ports:
      - "2379:2379"
      - "2380:2380"
    entrypoint:
      - etcd
      - --enable-v2
      - --listen-client-urls=http://0.0.0.0:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=mys3cr3ttok3n
    command:
      - --name=etcd0
      - --advertise-client-urls=http://etcd0:2379
      - --initial-advertise-peer-urls=http://etcd0:2380
    volumes:
      - etcd0:/etcd_data
  etcd1:
    image: quay.io/coreos/etcd:v3.5.16
    # internal: 2379 for client communication
    # internal: 2380 for etcd nodes communication
    # localhost: 3379 for client communication
    # localhost: 3380 for etcd nodes communication
    ports:
      - "3379:2379" 
      - "3380:2380"  
    entrypoint:
      - etcd
      - --enable-v2
      - --listen-client-urls=http://0.0.0.0:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=mys3cr3ttok3n
    command:
      - --name=etcd1
      - --advertise-client-urls=http://etcd1:2379
      - --initial-advertise-peer-urls=http://etcd1:2380
    volumes:
      - etcd1:/etcd_data

  etcd2:
    image: quay.io/coreos/etcd:v3.5.16
    # internal: 2379 for client communication
    # internal: 2380 for etcd nodes communication
    # localhost: 4379 for client communication
    # localhost: 4380 for etcd nodes communication
    ports:
      - "4379:2379"  
      - "4380:2380" 
    entrypoint:
      - etcd
      - --enable-v2
      - --listen-client-urls=http://0.0.0.0:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=mys3cr3ttok3n
    command:
      - --name=etcd2
      - --advertise-client-urls=http://etcd2:2379
      - --initial-advertise-peer-urls=http://etcd2:2380
    volumes:
      - etcd2:/etcd_data

volumes:
  etcd0:
  etcd1:
  etcd2:

